services:
  - type: web
    name: handwriting-decoder-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt && apt-get update && apt-get install -y tesseract-ocr
    startCommand: cd backend && python manage.py migrate && gunicorn handwriting_decoder.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.16
      - key: DATABASE_URL
        fromDatabase:
          name: handwriting-decoder-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: handwriting-decoder-db
    databaseName: handwriting_decoder
    plan: free